### ISSUE TITLE
cli.py print statements

### ISSUE THREAD

**Issue by snmpboy** [SimpleLegal/pocket_protector#5]
Cli.py module has a 2.7 based print statements as opposed to 3.x print statements.

**Comment by mahmoud** [comment]
Hey Mitch! You're absolutely right. Pocket Protector actually has several py3 incompatibilities, including one of the libraries it relies on. Fixes for that and much more are all on the face-refactor branch, which is py3 compatible. Look for that in the coming weeks (unless you need it much sooner ;) ). Thanks for the report!

**Comment by JelleZijlstra** [comment]
Hey @mahmoud, any updates on Python 3 compatibility?

**Comment by mahmoud** [comment]
You know, it's taken a little while, but time appears to have healed all wounds; pocket protector is now python 3 compatible :)
